name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy api || true  # allow partial unknowns for now
      - name: Tests (pytest)
        run: pytest -q
      - name: OWASP LLM Top-10 placeholder
        run: |
          echo "Running placeholder checks for prompt injection & output handling" \
          && grep -R "eval(" -n api || true
      - name: OWASP API Top-10 placeholder
        run: |
          echo "Ensuring auth on sensitive endpoints" \
          && grep -R "@app.get(\"/metrics\")" -n api && echo "Metrics open by design" || true
